baseURL = 'https://paipaiio.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

# æ„å»ºè®¾ç½®
[pagination]
  pagerSize = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

########################
# è¾“å‡ºæ ¼å¼ï¼ˆRSS / SEOï¼‰
########################
[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[outputs.page]
page = ["HTML"]
search = ["JSON"]

########################
# PaperMod å‚æ•°
########################
[params]
comments = true

enableSearch = true

# å†…å®¹ä¸»å…¥å£ï¼ˆéå¸¸é‡è¦ï¼‰
mainSections = ["posts"]

# ä¸»é¢˜æ¨¡å¼
defaultTheme = "auto"        # auto / light / dark
disableThemeToggle = false

# é˜…è¯»ä½“éªŒ
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false

# åˆ—è¡¨ä¸æ‘˜è¦
hideSummary = false
UseHugoToc = true
TocOpen = false

# SEO
env = "production"
description = "ä¸€ä¸ªé•¿æœŸç»´æŠ¤çš„ä¸ªäººåšå®¢ï¼Œè®°å½•æŠ€æœ¯ä¸æ€è€ƒ"

########################
# é¦–é¡µï¼šProfileMode
########################
[params.profileMode]
enabled = true
title = "MuskZhou"
subtitle = "å†™ç‚¹ä¸œè¥¿ï¼Œè®°å½•æŠ˜è…¾"
imageUrl = "img/avatar.png"
imageTitle = "avatar"
imageWidth = 120
imageHeight = 120

# ProfileMode æŒ‰é’®ï¼ˆå¯é€‰ï¼‰
[[params.profileMode.buttons]]
name = "æ–‡ç« "
url = "/posts/"

[[params.profileMode.buttons]]
name = "å…³äº"
url = "/about/"

########################
# ç¤¾äº¤é“¾æ¥ï¼ˆå³ä¸‹è§’ / about ç”¨ï¼‰
########################
[[params.socialIcons]]
name = "github"
url = "https://github.com/paipaiio"

[[params.socialIcons]]
name = "email"
url = "mailto:MuskZhouMQ@outlook.com"

[params.giscus]
repo = "paipaiio/paipaiio.github.io"
repoId = "R_kgDORI5CQg"
category = "Comments"
categoryId = "DIC_kwDORI5CQs4C15eQ"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "transparent_dark"
lang = "zh-CN"

########################
# é¡¶éƒ¨èœå•
########################
[[menu.main]]
name = "é¦–é¡µ"
url = "/"
weight = 1

[[menu.main]]
name = "æ–‡ç« "
url = "/posts/"
weight = 2

[[menu.main]]
name = "å…³äº"
url = "/about/"
weight = 3

[[menu.main]]
name = "ğŸ”"
url = "/search/"
weight = 4



########################
# Markdown æ¸²æŸ“ï¼ˆæ¨èï¼‰
########################
[markup]

  [markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = true

  [markup.goldmark.renderer]
  unsafe = true


