baseURL = 'https://paipaiio.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

# 构建设置
[pagination]
  pagerSize = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

########################
# 输出格式（RSS / SEO）
########################
[outputs]
home = ["HTML", "RSS", "JSON"]

########################
# PaperMod 参数
########################
[params]
comments = true

# 内容主入口（非常重要）
mainSections = ["posts"]

# 主题模式
defaultTheme = "auto"        # auto / light / dark
disableThemeToggle = false

# 阅读体验
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false

# 列表与摘要
hideSummary = false
UseHugoToc = true
TocOpen = false

# SEO
env = "production"
description = "一个长期维护的个人博客，记录技术与思考"

########################
# 首页：ProfileMode
########################
[params.profileMode]
enabled = true
title = "MuskZhou"
subtitle = "写点东西，记录折腾"
imageUrl = "img/avatar.png"
imageTitle = "avatar"
imageWidth = 120
imageHeight = 120

# ProfileMode 按钮（可选）
[[params.profileMode.buttons]]
name = "文章"
url = "/posts/"

[[params.profileMode.buttons]]
name = "关于"
url = "/about/"

########################
# 社交链接（右下角 / about 用）
########################
[[params.socialIcons]]
name = "github"
url = "https://github.com/paipaiio"

[[params.socialIcons]]
name = "email"
url = "MuskZhouMQ@outlook.com"

########################
# 顶部菜单
########################
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 2

[[menu.main]]
name = "关于"
url = "/about/"
weight = 3

########################
# Markdown 渲染（推荐）
########################
[markup]

  [markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = true

  [markup.goldmark.renderer]
  unsafe = true


[params.giscus]
repo = "paipaiio/paipaiio.github.io"
repoId = "R_kgDORI5CQg"
category = "Comments"
categoryId = "DIC_kwDORI5CQs4C15eQ"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"